### ISSUE TITLE
Trouble under Windows

### ISSUE THREAD

**Issue by tester0077** [foxguardsolutions/wxpython#3]
Being relatively new to Docker, I just tried to build a test container for an app with
 docker build -t wpet .
in a directory with the given Dockerfile

the last of the output:```

 > [4/4] RUN pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/debian-9 wxPython:
#7 1.237 Looking in links: https://extras.wxpython.org/wxPython4/extras/linux/gtk3/debian-9
#7 2.445 Collecting wxPython
#7 2.528   Downloading wxPython-4.2.0.tar.gz (71.0 MB)
#7 13.42     ERROR: Command errored out with exit status 1:
#7 13.42      command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zxcszj9u/wxPython/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zxcszj9u/wxPython/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-zxcszj9u/wxPython/pip-egg-info
#7 13.42          cwd: /tmp/pip-install-zxcszj9u/wxPython/
#7 13.42     Complete output (7 lines):
#7 13.42     Traceback (most recent call last):
#7 13.42       File "<string>", line 1, in <module>
#7 13.42       File "/tmp/pip-install-zxcszj9u/wxPython/setup.py", line 27, in <module>
#7 13.42         from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
#7 13.42       File "/tmp/pip-install-zxcszj9u/wxPython/buildtools/config.py", line 30, in <module>
#7 13.42         from attrdict import AttrDict
#7 13.42     ModuleNotFoundError: No module named 'attrdict'
#7 13.42     ----------------------------------------
#7 13.70 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.#7 14.76 WARNING: You are using pip version 20.0.2; however, version 22.3.1 is available.
#7 14.76 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
```
Any tips on where I am going wrong?

**Comment by tester0077** [comment]
After actually trying to run the test project, it seems that wxPython was installed despite the error messages.
Hence disregard my question.
